FROM node:22-alpine

RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm@10

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --config.dangerouslyAllowAllBuilds

COPY . .
ENV DATABASE_URL="postgresql://user:pass@localhost:5432/dummy"
RUN pnpm build-db

EXPOSE 3000
ENV HOSTNAME=0.0.0.0

CMD ["pnpm", "dev"]
