-- Fork-local column: the src_ prefix keeps this clear of any hostname column
-- upstream may add to heatmap_event later.
-- AlterTable (generated by `prisma migrate diff`, hardened with IF NOT EXISTS)
ALTER TABLE "heatmap_event" ADD COLUMN IF NOT EXISTS "src_hostname" VARCHAR(100);

-- Backfill order: deterministic passes (1-4) run before the statistical
-- fingerprint (6), which learns from their output; the consistency veto runs
-- both before it (5, so bad attributions cannot poison its reference data)
-- and after it (7, as the final say).

-- Backfill pass 1: assign the hostname of the visit's pageviews for the same
-- url_path, but only when they all agree on a single hostname. When the visit
-- saw the same path on multiple hostnames (e.g. "/" on both the main site and
-- the docs site, often in two tabs) the click cannot be attributed reliably
-- and is left unresolved rather than polluting one host's heatmap.
UPDATE "heatmap_event" h
SET "src_hostname" = m."hostname"
FROM (
    SELECT h2."heatmap_event_id", min(we."hostname") AS "hostname"
    FROM "heatmap_event" h2
    JOIN "website_event" we
        ON we."visit_id" = h2."visit_id"
        AND we."url_path" = h2."url_path"
    WHERE h2."src_hostname" IS NULL
        AND we."hostname" IS NOT NULL
    GROUP BY h2."heatmap_event_id"
    HAVING count(DISTINCT we."hostname") = 1
) m
WHERE h."heatmap_event_id" = m."heatmap_event_id";

-- Backfill pass 2: a url_path that has only ever been served by one hostname
-- identifies that hostname regardless of the visit's history. Runs before the
-- visit-unanimity fallback so a globally exclusive path wins over misleading
-- visit evidence (a visit whose tracked pageviews were all on another host).
UPDATE "heatmap_event" h
SET "src_hostname" = p."hostname"
FROM (
    SELECT "url_path", min("hostname") AS "hostname"
    FROM "website_event"
    WHERE "hostname" IS NOT NULL
    GROUP BY "url_path"
    HAVING count(DISTINCT "hostname") = 1
) p
WHERE h."src_hostname" IS NULL
    AND h."url_path" = p."url_path";

-- Backfill pass 3 (deployment knowledge): docs did not have
-- heatmap tracking until its heatmap PR reached production on
-- 2026-07-15 17:12 UTC, so no event recorded before then can belong to it.
-- (Its *.pages.dev preview deployments were emitting earlier, so only the
-- production hostname is excluded.) For older unresolved events, drop docs
-- from the visit's candidates and assign when exactly one hostname remains.
UPDATE "heatmap_event" h
SET "src_hostname" = v."hostname"
FROM (
    SELECT "visit_id", min("hostname") AS "hostname"
    FROM "website_event"
    WHERE "hostname" IS NOT NULL
        AND "hostname" <> 'docs.source.network'
    GROUP BY "visit_id"
    HAVING count(DISTINCT "hostname") = 1
) v
WHERE h."src_hostname" IS NULL
    AND h."created_at" < '2026-07-15 17:12:00+00'
    AND h."visit_id" = v."visit_id";

-- Backfill pass 4 (fallback): events with no same-path pageview evidence take
-- the visit's hostname when the entire visit stayed on one hostname.
UPDATE "heatmap_event" h
SET "src_hostname" = v."hostname"
FROM (
    SELECT "visit_id", min("hostname") AS "hostname"
    FROM "website_event"
    WHERE "hostname" IS NOT NULL
    GROUP BY "visit_id"
    HAVING count(DISTINCT "hostname") = 1
) v
WHERE h."src_hostname" IS NULL
    AND h."visit_id" = v."visit_id";

-- Backfill pass 5 (consistency veto, first application): an attribution is
-- only possible if the assigned hostname ever served that path. Catches
-- visits whose pageview evidence was unanimous but wrong (e.g. the user
-- interacted with another site's tab while their tracked pageviews were all
-- on this one). Running it here keeps impossible attributions out of the
-- fingerprint pass's reference data.
UPDATE "heatmap_event" h
SET "src_hostname" = NULL
WHERE h."src_hostname" IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM "website_event" we
        WHERE we."hostname" = h."src_hostname"
            AND we."url_path" = h."url_path"
    );

-- Backfill pass 6 (dimension fingerprint): remaining events are paths served
-- by multiple hostnames (e.g. "/" on both the main site and docs). Candidates
-- are limited to hostnames the event's own visit touched — a click can only
-- belong to a host its visit visited, which excludes height-identical clones
-- such as preview deployments. The event's recorded page_h is compared to the
-- median page_h of already-attributed events per candidate (hostname,
-- url_path); assign only when the height sits close to one candidate's
-- cluster (within ~1.5x) and clearly away from every other candidate (>2.5x
-- off), otherwise leave unresolved.
UPDATE "heatmap_event" h
SET "src_hostname" = b."hostname"
FROM (
    SELECT
        s."heatmap_event_id",
        (array_agg(s."hostname" ORDER BY s.dist))[1] AS "hostname",
        (array_agg(s.dist ORDER BY s.dist))[1] AS best_dist,
        (array_agg(s.dist ORDER BY s.dist))[2] AS second_dist
    FROM (
        SELECT
            h2."heatmap_event_id",
            r."hostname",
            abs(ln(h2."page_h"::float / r.ref_h)) AS dist
        FROM "heatmap_event" h2
        JOIN (
            SELECT DISTINCT "visit_id", "hostname"
            FROM "website_event"
            WHERE "hostname" IS NOT NULL
        ) vh ON vh."visit_id" = h2."visit_id"
        JOIN (
            SELECT
                "src_hostname" AS "hostname",
                "url_path",
                percentile_cont(0.5) WITHIN GROUP (ORDER BY "page_h") AS ref_h
            FROM "heatmap_event"
            WHERE "src_hostname" IS NOT NULL
                AND "page_h" > 0
            GROUP BY 1, 2
        ) r ON r."url_path" = h2."url_path"
            AND r."hostname" = vh."hostname"
        WHERE h2."src_hostname" IS NULL
            AND h2."page_h" > 0
            AND r.ref_h > 0
    ) s
    GROUP BY s."heatmap_event_id"
) b
WHERE h."heatmap_event_id" = b."heatmap_event_id"
    AND b.best_dist < ln(1.5)
    AND (b.second_dist IS NULL OR b.second_dist > ln(2.5));

-- Backfill pass 7 (consistency veto, final say): re-applied after the
-- fingerprint so no statistical assignment can name a hostname that never
-- served the path.
UPDATE "heatmap_event" h
SET "src_hostname" = NULL
WHERE h."src_hostname" IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM "website_event" we
        WHERE we."hostname" = h."src_hostname"
            AND we."url_path" = h."url_path"
    );

-- Rows still null are genuinely ambiguous; they appear under "Unknown host"
-- and age out of the reporting window.
